import { useState, useMemo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { FileText, FileJson, FileDown, Eye, Check } from 'lucide-react';
import { useAnalysis } from '../../lib/AnalysisContext';

const formats = [
  { id: 'pdf', label: 'PDF', icon: FileText, desc: 'Printable document' },
  { id: 'docx', label: 'DOCX', icon: FileText, desc: 'Word document' },
  { id: 'markdown', label: 'Markdown', icon: FileDown, desc: 'Structured .md file' },
  { id: 'json', label: 'JSON', icon: FileJson, desc: 'Structured data' }
];

function generateMarkdown({ doc, analysis }) {
  let md = `# ${doc?.filename || 'Document Analysis'}\n\n`;
  md += `> Generated by TechBrief AI\n\n`;

  if (analysis?.summary_executive) {
    md += `## Executive Summary\n\n${analysis.summary_executive}\n\n`;
  }
  if (analysis?.summary_30s) {
    md += `## Quick Summary\n\n${analysis.summary_30s}\n\n`;
  }
  if (analysis?.summary_detailed) {
    md += `## Detailed Summary\n\n${analysis.summary_detailed}\n\n`;
  }
  if (analysis?.summary_bullet?.length) {
    md += `## Key Points\n\n`;
    analysis.summary_bullet.forEach(b => { md += `- ${b}\n`; });
    md += '\n';
  }
  if (analysis?.key_findings?.length) {
    md += `## Key Findings\n\n`;
    analysis.key_findings.forEach(f => { md += `- ${f}\n`; });
    md += '\n';
  }
  if (analysis?.keywords?.length) {
    md += `## Keywords\n\n${analysis.keywords.join(', ')}\n\n`;
  }
  if (analysis?.metrics?.length) {
    md += `## Metrics\n\n| Label | Value | Category |\n|-------|-------|----------|\n`;
    analysis.metrics.forEach(m => { md += `| ${m.label} | ${m.value} | ${m.category} |\n`; });
    md += '\n';
  }

  return md;
}

function generateHTML({ doc, analysis }) {
  const md = generateMarkdown({ doc, analysis });
  return `<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><title>${doc?.filename || 'Analysis'}</title>
<style>
  body { font-family: Inter, system-ui, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; line-height: 1.6; color: #1e293b; }
  h1 { font-size: 28px; background: linear-gradient(135deg, #3B82F6, #8B5CF6); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }
  h2 { font-size: 20px; color: #3B82F6; margin-top: 24px; }
  h3 { font-size: 16px; color: #64748b; }
  ul { padding-left: 20px; }
  li { margin: 4px 0; }
  table { width: 100%; border-collapse: collapse; margin: 12px 0; }
  th, td { padding: 8px 12px; border: 1px solid #e2e8f0; text-align: left; }
  th { background: #f8fafc; font-weight: 600; }
  blockquote { border-left: 3px solid #3B82F6; padding-left: 16px; color: #64748b; }
</style></head>
<body>${md.split('\n').map(line => {
    if (line.startsWith('# ')) return `<h1>${line.slice(2)}</h1>`;
    if (line.startsWith('## ')) return `<h2>${line.slice(3)}</h2>`;
    if (line.startsWith('### ')) return `<h3>${line.slice(4)}</h3>`;
    if (line.startsWith('- ')) return `<li>${line.slice(2)}</li>`;
    if (line.startsWith('|')) return `<p>${line}</p>`;
    if (line.trim() === '') return '<br/>';
    return `<p>${line}</p>`;
  }).join('\n')}</body></html>`;
}

export default function ExportTab() {
  const { analysis, currentDoc } = useAnalysis();
  const [selectedFormat, setSelectedFormat] = useState('markdown');
  const [exported, setExported] = useState(false);

  const content = useMemo(() => {
    if (!analysis && !currentDoc) return '';
    switch (selectedFormat) {
      case 'markdown': return generateMarkdown({ doc: currentDoc, analysis });
      case 'json': return JSON.stringify({ document: currentDoc, analysis }, null, 2);
      case 'docx':
      case 'pdf': return generateHTML({ doc: currentDoc, analysis });
      default: return '';
    }
  }, [selectedFormat, analysis, currentDoc]);

  const handleExport = () => {
    if (selectedFormat === 'pdf') {
      const printWindow = window.open('', '_blank');
      printWindow.document.write(content);
      printWindow.document.close();
      printWindow.print();
    } else if (selectedFormat === 'docx') {
      const blob = new Blob([content], { type: 'application/msword' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${currentDoc?.filename || 'analysis'}.doc`;
      a.click();
      URL.revokeObjectURL(url);
    } else if (selectedFormat === 'json') {
      const blob = new Blob([content], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${currentDoc?.filename || 'analysis'}.json`;
      a.click();
      URL.revokeObjectURL(url);
    } else {
      const blob = new Blob([content], { type: 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${currentDoc?.filename || 'analysis'}.md`;
      a.click();
      URL.revokeObjectURL(url);
    }

    setExported(true);
    setTimeout(() => setExported(false), 3000);
  };

  if (!currentDoc) {
    return (
      <div className="flex flex-col items-center justify-center py-20 text-center">
        <div className="w-16 h-16 rounded-2xl bg-slate-100 dark:bg-dark-card flex items-center justify-center mb-4">
          <FileDown className="w-8 h-8 text-slate-300 dark:text-slate-600" />
        </div>
        <h3 className="text-lg font-semibold text-slate-500 dark:text-slate-400">No document to export</h3>
        <p className="text-sm text-slate-400 mt-1">Upload and analyze a document first</p>
      </div>
    );
  }

  return (
    <div className="max-w-5xl mx-auto space-y-8">
      <div>
        <h2 className="text-2xl font-bold gradient-text">Export</h2>
        <p className="text-slate-500 dark:text-slate-400 mt-1">Download your analysis in various formats</p>
      </div>

      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        {formats.map(f => (
          <motion.button
            key={f.id}
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.98 }}
            onClick={() => setSelectedFormat(f.id)}
            className={`glass rounded-2xl p-4 text-center transition-all ${
              selectedFormat === f.id
                ? 'ring-2 ring-accent shadow-lg shadow-accent/10'
                : 'hover:bg-slate-50 dark:hover:bg-dark-card/50'
            }`}
          >
            <f.icon className={`w-8 h-8 mx-auto mb-2 ${selectedFormat === f.id ? 'text-accent' : 'text-slate-400'}`} />
            <p className="text-sm font-semibold text-slate-700 dark:text-slate-300">{f.label}</p>
            <p className="text-[10px] text-slate-400 mt-0.5">{f.desc}</p>
          </motion.button>
        ))}
      </div>

      <div className="glass rounded-2xl overflow-hidden">
        <div className="flex items-center justify-between px-4 py-3 border-b border-slate-200 dark:border-dark-border">
          <div className="flex items-center gap-2 text-sm text-slate-500 dark:text-slate-400">
            <Eye className="w-4 h-4" /> Preview
          </div>
          <span className="text-xs text-slate-400">{content.length} chars</span>
        </div>
        <pre className="p-4 text-xs text-slate-600 dark:text-slate-400 overflow-auto max-h-[300px] leading-relaxed whitespace-pre-wrap font-mono">
          {content.slice(0, 3000)}
          {content.length > 3000 ? '\n... (truncated)' : ''}
        </pre>
      </div>

      <motion.button
        whileHover={{ scale: 1.01 }}
        whileTap={{ scale: 0.99 }}
        onClick={handleExport}
        className={`w-full py-4 rounded-2xl text-sm font-semibold transition-all flex items-center justify-center gap-2 ${
          exported
            ? 'bg-emerald-500 text-white'
            : 'bg-gradient-to-r from-accent to-accent-secondary text-white hover:opacity-90'
        }`}
      >
        {exported ? (
          <>
            <Check className="w-5 h-5" /> Exported Successfully!
          </>
        ) : (
          <>
            <FileDown className="w-5 h-5" /> Export as {formats.find(f => f.id === selectedFormat)?.label}
          </>
        )}
      </motion.button>
    </div>
  );
}
